export * from './lib/permissions.js';
export * from './lib/auth.js';
export * from './lib/patient.js';
export * from './lib/api-error.js';
export * from './lib/historia-clinica.js';
export * from './lib/valoracion.js';
export * from './lib/photo.js';
export * from './lib/treatment.js';
export * from './lib/consent.js';
